export enum NodeType {
  INITIAL = "INITIAL",
  MANUAL_TRIGGER = "MANUAL_TRIGGER",
  HTTP_REQUEST = "HTTP_REQUEST",

  ACTION = "ACTION",
  CONDITION = "CONDITION",
  LOOP = "LOOP",

  // AI stuff
  GEMINI_AI = "GEMINI_AI",
  OPENAI_AI = "OPENAI_AI",
}
