export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 5,
  MIN_PAGE_SIZE: 1,
  MAX_PAGE_SIZE: 100,
  DEFAULT_SORT: "createdAt",
  DEFAULT_SORT_ORDER: "desc",
  DEFAULT_SEARCH: "",
}

export const USUAL_DEBOUNCE_MS = 500
